### ISSUE TITLE
Update dark mode icon to be SVG and works on both themes

### ISSUE THREAD

**Issue by natachadelarosa** [subspace/blockscout-frontend#2]
Currently, when we collapse the side menu in the dark theme, the icon doesn't show properly:

![Image](https://github.com/subspace/blockscout-frontend/assets/5139220/29a235f6-2ec8-4906-87a6-ee6f9554d9b1)

We need to add an updated version of the icon that is SVG and can change according to the theme selected.

Will add it here when we have the icon available.

**Comment by chrissotraidis** [comment]
Thinking this could be an easy task for @marc-aurele-besner to take on. @natachadelarosa let me know what you think.
